create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  type text not null default '기타',
  content text not null,
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;
