create extension if not exists pg_trgm;

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  answer_raw text not null default '',
  answer_normalized text not null default '',
  is_correct boolean not null default false,
  is_pass boolean not null default false,
  is_valid boolean not null default false,
  is_daily_case boolean not null default false,
  similarity_score numeric(5, 4) not null default 0,
  xp_earned integer not null default 0,
  combo_after integer not null default 0,
  created_at timestamptz not null default now(),
  unique (challenge_id, user_id)
);

create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  interpreter_xp integer not null default 0,
  uploader_xp integer not null default 0,
  activity_streak integer not null default 0,
  last_contribution_date date,
  daily_valid_activity_count integer not null default 0,
  daily_activity_date date,
  daily_bonus_date date,
  current_combo integer not null default 0,
  max_combo integer not null default 0,
  combo_date date,
  updated_at timestamptz not null default now()
);

create table if not exists public.xp_ledger (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  track text not null check (track in ('interpreter', 'uploader')),
  event_type text not null,
  event_key text not null,
  amount integer not null,
  challenge_id bigint,
  created_at timestamptz not null default now(),
  unique (user_id, event_key)
);

create table if not exists public.daily_cases (
  id bigint generated by default as identity primary key,
  challenge_id bigint not null,
  case_date date not null unique,
  selection_type text not null default 'manual' check (selection_type in ('manual', 'fallback')),
  status text not null default 'scheduled' check (status in ('scheduled', 'active', 'ended')),
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  challenge_id bigint,
  title text not null,
  body text not null,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  unique (user_id, type, challenge_id)
);

alter table public.attempts enable row level security;
alter table public.user_stats enable row level security;
alter table public.xp_ledger enable row level security;
alter table public.daily_cases enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "attempts visible to participant or author" on public.attempts;
create policy "attempts visible to participant or author"
on public.attempts for select to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.challenges
    where challenges.id = attempts.challenge_id
      and challenges.author_id = auth.uid()
  )
);

drop policy if exists "users read their stats" on public.user_stats;
create policy "users read their stats"
on public.user_stats for select to authenticated
using (user_id = auth.uid());

drop policy if exists "users read their xp" on public.xp_ledger;
create policy "users read their xp"
on public.xp_ledger for select to authenticated
using (user_id = auth.uid());

drop policy if exists "daily cases are public" on public.daily_cases;
create policy "daily cases are public"
on public.daily_cases for select to authenticated
using (true);

drop policy if exists "users read their notifications" on public.notifications;
create policy "users read their notifications"
on public.notifications for select to authenticated
using (user_id = auth.uid());

drop policy if exists "users mark notifications read" on public.notifications;
create policy "users mark notifications read"
on public.notifications for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create or replace function public.bbiduru_normalize_answer(value text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(coalesce(value, ''), '[^[:alnum:]가-힣]+', '', 'g'));
$$;

create or replace function public.bbiduru_award_passive_xp(
  p_user_id uuid,
  p_track text,
  p_amount integer,
  p_event_type text,
  p_event_key text,
  p_challenge_id bigint default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_count integer;
begin
  insert into public.user_stats (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  insert into public.xp_ledger (user_id, track, event_type, event_key, amount, challenge_id)
  values (p_user_id, p_track, p_event_type, p_event_key, p_amount, p_challenge_id)
  on conflict (user_id, event_key) do nothing;
  get diagnostics inserted_count = row_count;

  if inserted_count = 0 then
    return false;
  end if;

  update public.user_stats
  set interpreter_xp = interpreter_xp + case when p_track = 'interpreter' then p_amount else 0 end,
      uploader_xp = uploader_xp + case when p_track = 'uploader' then p_amount else 0 end,
      updated_at = now()
  where user_id = p_user_id;
  return true;
end;
$$;

create or replace function public.bbiduru_apply_activity(
  p_user_id uuid,
  p_track text,
  p_amount integer,
  p_correct boolean,
  p_event_key text,
  p_challenge_id bigint default null
)
returns public.user_stats
language plpgsql
security definer
set search_path = public
as $$
declare
  today date := (now() at time zone 'Asia/Seoul')::date;
  current_stats public.user_stats;
  inserted_count integer;
  new_daily_count integer;
  bonus integer := 0;
  streak_bonus integer := 0;
  new_streak integer;
begin
  insert into public.user_stats (user_id)
  values (p_user_id)
  on conflict (user_id) do nothing;

  select * into current_stats
  from public.user_stats
  where user_id = p_user_id
  for update;

  insert into public.xp_ledger (user_id, track, event_type, event_key, amount, challenge_id)
  values (p_user_id, p_track, 'activity', p_event_key, p_amount, p_challenge_id)
  on conflict (user_id, event_key) do nothing;
  get diagnostics inserted_count = row_count;

  if inserted_count = 0 then
    return current_stats;
  end if;

  new_daily_count := case
    when current_stats.daily_activity_date = today then current_stats.daily_valid_activity_count + 1
    else 1
  end;

  new_streak := case
    when current_stats.last_contribution_date = today then current_stats.activity_streak
    when current_stats.last_contribution_date = today - 1 then current_stats.activity_streak + 1
    else 1
  end;

  if current_stats.last_contribution_date is distinct from today and new_streak = 3 then
    streak_bonus := 10;
    insert into public.xp_ledger (user_id, track, event_type, event_key, amount, challenge_id)
    values (p_user_id, p_track, 'streak_bonus', 'streak_bonus:3', streak_bonus, p_challenge_id)
    on conflict (user_id, event_key) do nothing;
    get diagnostics inserted_count = row_count;
    if inserted_count = 0 then
      streak_bonus := 0;
    end if;
  end if;

  if new_daily_count >= 3 and current_stats.daily_bonus_date is distinct from today then
    bonus := 10;
    insert into public.xp_ledger (user_id, track, event_type, event_key, amount, challenge_id)
    values (p_user_id, p_track, 'daily_bonus', 'daily_bonus:' || today::text, bonus, p_challenge_id)
    on conflict (user_id, event_key) do nothing;
  end if;

  update public.user_stats
  set interpreter_xp = interpreter_xp + case when p_track = 'interpreter' then p_amount + bonus + streak_bonus else 0 end,
      uploader_xp = uploader_xp + case when p_track = 'uploader' then p_amount + bonus + streak_bonus else 0 end,
      activity_streak = new_streak,
      last_contribution_date = today,
      daily_valid_activity_count = new_daily_count,
      daily_activity_date = today,
      daily_bonus_date = case when bonus > 0 then today else daily_bonus_date end,
      current_combo = case
        when p_track <> 'interpreter' then current_combo
        when p_correct then current_combo + 1
        else 0
      end,
      max_combo = greatest(
        max_combo,
        case
          when p_track = 'interpreter' and p_correct then
            current_combo + 1
          else 0
        end
      ),
      combo_date = case when p_track = 'interpreter' then today else combo_date end,
      updated_at = now()
  where user_id = p_user_id
  returning * into current_stats;

  return current_stats;
end;
$$;

create or replace function public.submit_attempt(
  p_challenge_id bigint,
  p_answer text,
  p_is_pass boolean default false,
  p_is_daily boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  current_user_id uuid := auth.uid();
  current_challenge public.challenges%rowtype;
  normalized_answer text;
  normalized_target text;
  score numeric := 0;
  correct boolean := false;
  valid boolean := false;
  daily_case boolean := false;
  base_xp integer := 0;
  before_xp integer := 0;
  after_stats public.user_stats;
  attempt_row public.attempts%rowtype;
  valid_tries integer := 0;
  correct_tries integer := 0;
  computed_rate integer := 0;
  owner_id uuid;
begin
  if current_user_id is null then
    raise exception 'Authentication required';
  end if;

  select * into current_challenge
  from public.challenges
  where id = p_challenge_id;

  if not found then
    raise exception 'Challenge not found';
  end if;

  select * into attempt_row
  from public.attempts
  where challenge_id = p_challenge_id and user_id = current_user_id;
  if found then
    select * into after_stats from public.user_stats where user_id = current_user_id;
    return jsonb_build_object(
      'attempt', to_jsonb(attempt_row),
      'stats', to_jsonb(after_stats),
      'challenge_stats', jsonb_build_object(
        'tries', current_challenge.tries,
        'success_rate', current_challenge.success_rate
      )
    );
  end if;

  normalized_answer := public.bbiduru_normalize_answer(p_answer);
  normalized_target := public.bbiduru_normalize_answer(current_challenge.answer);
  valid := not p_is_pass
    and length(normalized_answer) >= 2
    and current_challenge.author_id is distinct from current_user_id;

  if valid then
    score := similarity(normalized_target, normalized_answer);
    correct := score > 0.55;
    daily_case := (
      exists (
        select 1 from public.daily_cases
        where case_date = (now() at time zone 'Asia/Seoul')::date
          and status = 'active'
          and challenge_id = p_challenge_id
      )
      or (
        p_is_daily
        and not exists (
          select 1 from public.daily_cases
          where case_date = (now() at time zone 'Asia/Seoul')::date
            and status = 'active'
        )
      )
    ) and not exists (
      select 1 from public.xp_ledger
      where user_id = current_user_id
        and event_key = 'daily_case:' || (now() at time zone 'Asia/Seoul')::date::text
    );
    if daily_case then
      insert into public.xp_ledger (user_id, track, event_type, event_key, amount, challenge_id)
      values (
        current_user_id,
        'interpreter',
        'daily_case_marker',
        'daily_case:' || (now() at time zone 'Asia/Seoul')::date::text,
        0,
        p_challenge_id
      )
      on conflict (user_id, event_key) do nothing;
    end if;
    base_xp := 5
      + case when correct then 8 else 0 end
      + case when correct and current_challenge.success_rate < 30 then 5 else 0 end
      + case when daily_case then 3 else 0 end;

    select interpreter_xp into before_xp
    from public.user_stats where user_id = current_user_id;
    before_xp := coalesce(before_xp, 0);
    after_stats := public.bbiduru_apply_activity(
      current_user_id,
      'interpreter',
      base_xp,
      correct,
      'attempt:' || p_challenge_id::text,
      p_challenge_id
    );
  else
    insert into public.user_stats (user_id)
    values (current_user_id)
    on conflict (user_id) do nothing;
    update public.user_stats
    set current_combo = 0,
        combo_date = (now() at time zone 'Asia/Seoul')::date,
        updated_at = now()
    where user_id = current_user_id
    returning * into after_stats;
  end if;

  insert into public.attempts (
    challenge_id, user_id, answer_raw, answer_normalized, is_correct, is_pass,
    is_valid, is_daily_case, similarity_score, xp_earned, combo_after
  ) values (
    p_challenge_id, current_user_id, coalesce(p_answer, ''), normalized_answer,
    correct, p_is_pass, valid, daily_case, score,
    greatest(0, after_stats.interpreter_xp - before_xp), after_stats.current_combo
  )
  returning * into attempt_row;

  if valid then
    select count(*), count(*) filter (where is_correct)
    into valid_tries, correct_tries
    from public.attempts
    where challenge_id = p_challenge_id and is_valid and not is_pass;
    computed_rate := case
      when valid_tries = 0 then 0
      else round((correct_tries::numeric / valid_tries::numeric) * 100)::integer
    end;

    update public.challenges
    set tries = valid_tries,
        success_rate = computed_rate
    where id = p_challenge_id;

    owner_id := current_challenge.author_id;
    if owner_id is not null and valid_tries in (1, 5, 10) then
      insert into public.notifications (user_id, type, challenge_id, title, body)
      values (
        owner_id,
        case valid_tries when 1 then 'first_attempt' when 5 then 'report_ready' else 'report_final' end,
        p_challenge_id,
        case valid_tries when 1 then '첫 판독이 도착했어요' when 5 then '리포트가 준비됐어요' else '최종 악필력이 확정됐어요' end,
        case valid_tries when 1 then '내 글씨에 첫 판독이 달렸어요.' when 5 then '5명의 판독 결과를 확인해보세요.' else '10명의 판독으로 최종 난이도가 정해졌어요.' end
      )
      on conflict (user_id, type, challenge_id) do nothing;

      if valid_tries = 5 then
        perform public.bbiduru_award_passive_xp(owner_id, 'uploader', 10, 'five_attempts', 'five_attempts:' || p_challenge_id::text, p_challenge_id);
      elsif valid_tries = 10 then
        perform public.bbiduru_award_passive_xp(owner_id, 'uploader', 15, 'ten_attempts', 'ten_attempts:' || p_challenge_id::text, p_challenge_id);
        if computed_rate < 30 then
          perform public.bbiduru_award_passive_xp(owner_id, 'uploader', 10, 'hard_challenge', 'hard_challenge:' || p_challenge_id::text, p_challenge_id);
        end if;
      end if;
    end if;
  else
    valid_tries := current_challenge.tries;
    computed_rate := current_challenge.success_rate;
  end if;

  return jsonb_build_object(
    'attempt', to_jsonb(attempt_row),
    'stats', to_jsonb(after_stats),
    'challenge_stats', jsonb_build_object(
      'tries', valid_tries,
      'success_rate', computed_rate
    )
  );
end;
$$;

create or replace function public.bbiduru_on_challenge_created()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.author_id is not null then
    perform public.bbiduru_apply_activity(
      new.author_id,
      'uploader',
      5,
      null,
      'upload:' || new.id::text,
      new.id
    );
  end if;
  return new;
end;
$$;

drop trigger if exists bbiduru_challenge_created on public.challenges;
create trigger bbiduru_challenge_created
after insert on public.challenges
for each row execute function public.bbiduru_on_challenge_created();

grant execute on function public.submit_attempt(bigint, text, boolean, boolean) to authenticated;
